services:
  - type: web
    name: flashcard-maker-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://https://flashcard-maker-lyart.vercel.app/ 